project:
  type: website

website:
  title: "crugdemo2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: more_resources.qmd
        text: More Resources
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



